[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "#ff9e64"
index = 16

[[colors.indexed_colors]]
color = "#db4b4b"
index = 17

[colors.bright]
black = "#4a618a"
blue = "#5c91f7"
cyan = "#6ad8ff"
green = "#9ece6a"
magenta = "#b07af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[colors.normal]
black = "#5c768a"
blue = "#5c91f7"
cyan = "#6ad8ff"
green = "#9ece6a"
magenta = "#b07af7"
red = "#ff5c7d"
white = "#a9b1d6"
yellow = "#e0af68"

[colors.primary]
background = "#24283b"
foreground = "#bfc8ff"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrains Mono"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrains Mono"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Medium Italic"

[font.offset]
x = 0
y = 0

[scrolling]
history = 5000
multiplier = 5

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.82
position = "None"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2
