format = """
[┌─](bold black)\
[](yellow)\
[ ](bg:yellow fg:black)\
[](yellow)\
[─](bold black)\
[](red)\
$username\
$hostname\
[](red)\
[─](bold black)\
[](blue)\
[ ](bg:blue fg:black)\
$directory\
[](blue)\
[─](bold black)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$package\
$custom\
$sudo\
$fill\
$cmd_duration\
[─](bold black)\
[](green)\
$time\
[](green)\
$line_break\
$jobs\
$status\
$os\
$container\
$shell\
[└─](bold black)\
$character"""

[username]
style_user = "fg:black bg:red"
format = '[ $user@]($style)'
disabled = false
show_always = true

[hostname]
style = "fg:black bg:red"
ssh_only = false
format = '[$hostname]($style)'
disabled = false

[fill]
symbol = "─"
style = "bold black"

[directory]
style = "fg:black bg:blue"
format = "[$path]($style)"
read_only = ""
truncation_length = 8
truncation_symbol = '…/'
truncate_to_repo = false

# [git_branch]
# style = "fg:black bg:yellow"

[git_branch]
style = "fg:black bg:cyan"
symbol = ' '
format = '[](cyan)[$symbol$branch(:$remote_branch) ]($style)'
# ignore_branches = ['master', 'main']

[git_status]
# up_to_date = '✓'
style = "fg:black bg:cyan"
modified = ' ${count}'
untracked = ' ? ${count}'
staged = '[++\($count\)](green)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '[($all_status$ahead_behind)]($style)[](cyan)'

[cmd_duration]
style = "fg:black bg:purple"
format = '[](purple)[ $duration]($style)[](purple)'

[time]
disabled = false
style = "fg:black bg:green"
format = '[ $time]($style)'
time_format = '%I:%M%P'
utc_time_offset = '-5'

[character]
success_symbol = "[⮞](bold red)[⮞](bold yellow)[⮞](bold green)"
error_symbol = "[⮞](red)[⮞](red)[⮞](red)"
vicmd_symbol = "[❮](green)[❮](yellow)[❮](red)"
