format = """
[┌](bold black)\
[](yellow)\
$username\
$hostname\
[](yellow)\
[─](bold black)\
[](blue)\
[ ](bg:blue fg:#000000)\
$directory\
[](blue)\
$git_branch\
[─](bold black)\
$git_status\
$fill\
$cmd_duration\
[─](bold black)\
[](green)\
$time\
[](green)\
[ ](green)\
$line_break\
[└](bold black)\
$character"""

# [](yellow)\
# [ ](bg:yellow fg:#000000)\
# [](yellow)\
# [─](bold black)\
# 

add_newline = true

[username]
style_user = "fg:#000000 bg:yellow"
format = '[ $user@]($style)'
disabled = false
show_always = true

[hostname]
style = "fg:#000000 bg:yellow"
ssh_only = false
format = '[$hostname]($style)'
disabled = false

[fill]
symbol = "─"
style = "bold black"

[directory]
style = "fg:#000000 bg:blue"
format = "[$path]($style)"
read_only = ""
truncation_length = 4
truncation_symbol = '…/'
truncate_to_repo = false

# [git_branch]
# style = "fg:black bg:yellow"

[git_branch]
style = "fg:#000000 bg:cyan"
symbol = ' '
format = '([─](bold black)[](cyan)[$symbol$branch(:$remote_branch)]($style)[](cyan))'
# ignore_branches = ['master', 'main']

[git_status]
style = "fg:#000000 bg:purple"
up_to_date = ' '
modified = ' ${count} '
untracked = ' ? ${count} '
deleted = ' ✘ ${count}'
staged = '+ $count '
ahead = '↑ ${count}'
diverged = '⇅ ↑${ahead_count} ↓ ${behind_count}'
behind = '↓ ${count}'
# format = '[[](red)$all_status[](red)]($style)'
format = '([](purple)[$all_status$ahead_behind]($style)[](purple))'

[cmd_duration]
style = "fg:#000000 bg:red"
format = '[](red)[ $duration]($style)[](red)'

[time]
disabled = false
style = "fg:#000000 bg:green"
format = '[ $time]($style)'
time_format = '%I:%M%P'
utc_time_offset = '-5'

[character]
success_symbol = "[➤](red)[➤](yellow)[➤](green)"
error_symbol = "[➤](red)[➤](red)[➤](red)"
vicmd_symbol = "[❮](green)[❮](yellow)[❮](red)"
